### ISSUE TITLE
Link to ROM in README is broken

### ISSUE THREAD

**Issue by tobiasvl** [avivace/quadratino#1]
The link to download the ROM in `README.md` is broken.

It links to a non-existant ROM file in the repo, which has been removed. Having the assembled ROM in the same repo as the source is perhaps not a good idea anyway – consider making it a [release](https://github.com/avivace/quadratino/releases) with a binary attached instead?

**Comment by Micr0Bit** [comment]
>The link to download the ROM in README.md is broken.

confirmed.

**Comment by avivace** [comment]
https://github.com/avivace/quadratino/releases/tag/04302016 has a download link for the last binary I found.
