### ISSUE TITLE
Compilation on gdk-n not working, here is the solution

### ISSUE THREAD

**Issue by BenoitAdam** [avivace/quadratino#2]
just remove the useless   "mode=1;" at line 63

compiles fine with gdk-n with some warnings.

**Comment by BenoitAdam** [comment]
also change rand.h to <gb/rand.h>

**Comment by avivace** [comment]
Oh hey, thank you for your contribution! It's been years I haven't touched this project.

I'll make a separate branch to compile it with gbdk-n.

**Comment by avivace** [comment]
@BenoitAdam94 You are also welcome to send a Pull Request!

**Comment by BenoitAdam** [comment]
Oh thanks, I'm a beginner programmer !

I forked the project, I think it's better for now, I don't even know to use git commands, I have a weird error on VS Code with cigwin1.dll and can't solve it. It's better if I don't Pull Request for now :)

**Comment by BenoitAdam** [comment]
Thus, Pretty sure line-number don't match, not sure if it's me or VS Code... I copy/paste from github, that was a very bad idea I think

**Comment by avivace** [comment]
@BenoitAdam94 Oh, gotcha!
Feel free to join our [Discord server](https://discord.gg/gpBxq85) or take a look at our [Game Boy development resources](https://github.com/gbdev/awesome-gbdev).

Keep up the good work! :smile:
